### ISSUE TITLE
Clicking Edit Currently Crashes the app.

### ISSUE THREAD

**Issue by JaydenTChan** [Thirteam/CMPUT301W16T13#2]
To replicate: login, click a textbook in inventory and hit edit.

**Comment by xuefei1** [comment]
Edit function is not ready, however, with commit [84d9b73](https://github.com/Thirteam/CMPUT301W16T13/commit/84d9b730e721da68d2316fb4cdd972a864ec9261) the edit activity should show up now. However the app still might crash when attempting to save the updated item
