### ISSUE TITLE
If you login as a user with textbooks...

### ISSUE THREAD

**Issue by JaydenTChan** [Thirteam/CMPUT301W16T13#3]
And login with a user without you'll occasionally see their textbooks in your inventory.

**Comment by JaydenTChan** [comment]
The opposite can occur, no textbooks in an account can lead to no textbooks in the other account until you relog again.

**Comment by xuefei1** [comment]
Some users were created before changes were made to some model classes and this might be causing the issue. There are two known good users: username:a, password:a, username:b, password:b

**Comment by JaydenTChan** [comment]
Oh okay, we should probably clear and repopulate the database soon.
